c.colors.completion.fg = '#bbc2cf'
c.colors.completion.even.bg = '#2C323C'
c.colors.completion.odd.bg = '#2C323C'
c.colors.completion.category.bg = '#3B4048'
c.colors.completion.item.selected.fg = '#bbc2cf'
c.colors.completion.item.selected.bg = '#2257A0'
c.colors.completion.match.fg = '#C678DD'

c.colors.statusbar.command.fg = '#bbc2cf'
c.colors.statusbar.command.bg = '#2C323C'

c.colors.statusbar.normal.fg = '#bbc2cf'
c.colors.statusbar.normal.bg = '#2C323C'
c.colors.statusbar.insert.fg = '#282C34'
c.colors.statusbar.insert.bg = '#98C379'

c.colors.statusbar.url.success.https.fg = '#51AFEF'
c.colors.tabs.odd.fg = '#bbc2cf'
c.colors.tabs.odd.bg = '#2C323C'
c.colors.tabs.even.fg = '#bbc2cf'
c.colors.tabs.even.bg = '#2C323C'
c.colors.tabs.selected.odd.fg = '#282C34'
c.colors.tabs.selected.odd.bg = '#ECBE7B'
c.colors.tabs.selected.even.fg = '#282C34'
c.colors.tabs.selected.even.bg = '#ECBE7B'
c.colors.tabs.bar.bg = '#2C323C' # bad
c.colors.tabs.indicator.stop = '#51AFEF'
c.colors.hints.fg = '#FFFFFF'
c.colors.hints.bg = '#282C34'
c.colors.hints.match.fg = '#51AFEF'

c.colors.prompts.fg = '#bbc2cf'
c.colors.prompts.bg = '#2C323C'
c.colors.prompts.selected.bg = '#51AFEF'
